services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  app:
    image: simple2b/benjamin-back
    restart: always
    env_file:
      - .env
    environment:
      # APP_ENV: production # TODO remove in future
      DATABASE_URI: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-passwd}@db/db
    depends_on:
      - db
    ports:
      - 127.0.0.1:${LOCAL_WEB_PORT:-8000}:80

  admin:
    image: simple2b/benjamin-admin
    restart: always
    command: ['sh', 'start_server.sh']
    environment:
      APP_ENV: production
      DATABASE_URL: postgresql://${DATABASE_USERNAME:-postgres}:${DATABASE_PASSWORD:-passwd}@db/db
    ports:
      - 127.0.0.1:8009:80
    depends_on:
      - db
    env_file:
      - .env

  web:
    build: .
    depends_on:
      - app
    ports:
      - 127.0.0.1:3002:3000
    env_file:
      - .env

volumes:
  db_data:
