export const ICONS_NAME = {
  telephone: 'telephone',
  website: 'website',
  calendar: 'calendar',
  email: 'email',
  pause: 'pause',
  play: 'play',
  magnifyingGlass:'magnifying-glass',
  camera: 'photo-camera-interface-symbol-for-button',
  settings: 'settings',
  arrow: 'arrow',
  arrowRigth: 'arrow-right',
  selectingArrow: 'selecting-arrow',
  hastag: 'hastag',
  medal: 'medal',
  chevron: 'chevron',
  line: 'line',
  location: 'location-pin',
  navigation: 'navigation'
};
