import './globals.css';
import { OpenAPI } from '@/openapi';
import Providers from './providers';
import localFont from 'next/font/local';

const rajdhani = localFont({
  src: '../../public/fonts/Rajdhani-Regular.ttf',
  variable: '--rajdhani',
  display: 'swap',
});

const notoSans = localFont({
  src: '../../public/fonts/NotoSans-Regular.ttf',
  variable: '--noto-sans',
  display: 'swap',
});

OpenAPI.BASE = process.env.BACKEND_URL || '';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${rajdhani.variable} ${notoSans.variable} ${notoSans.className}`}
    >
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
