import './globals.css';
import { OpenAPI } from '@/openapi';
import { Providers } from '@/store/provider';

OpenAPI.BASE = process.env.BACKEND_URL || '';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
