import './globals.css';

import Providers from './providers';
import localFont from 'next/font/local';

const roboto = localFont({
  src: '../../public/fonts/RobotoFlex-Regular.ttf',
  variable: '--roboto',
  display: 'swap',
});

const rajdhani = localFont({
  src: '../../public/fonts/Rajdhani-Regular.ttf',
  variable: '--rajdhani',
  display: 'swap',
});

const rajdhaniSemiBold = localFont({
  src: '../../public/fonts/Rajdhani-SemiBold.ttf',
  variable: '--rajdhani-semi-bold',
  display: 'swap',
});

const notoSans = localFont({
  src: '../../public/fonts/NotoSans-Regular.ttf',
  variable: '--noto-sans',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${rajdhani.variable} ${rajdhaniSemiBold.variable} ${notoSans.variable} ${roboto.variable} ${notoSans.className} `}
    >
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
      </head>
      <body>
        <div
          id="page"
          className="fixed top-0 left-0 w-full h-full overflow-scroll"
        >
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
