# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Next.js app

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  DOCKER_LOGIN: simple2b
  IMAGE_REPO: simple2b/benjamin-front

jobs:
  test:
    runs-on: benjamin-front
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: yarn
      - name: check types
        run: yarn emit
      - name: check lint
        run: yarn lint
  build:
    runs-on: [benjamin-front]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: install packages
        run: yarn
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Build and Push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.IMAGE_REPO }}:latest
      - name: deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/operation-benjamin
            docker compose pull web && 
            docker compose up -d web &&
            docker system prune -f
